# Generated by Django 4.2.2 on 2023-06-12 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telebot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
